### ISSUE TITLE
Odd number of rows yields garbage in last row

### ISSUE THREAD

**Issue by onitake** [tzvetkoff/im2a#7]
In pixel mode, when processing images with an odd number of rows, the last line is filled up with garbage.

It would be better if the default background is used instead - or at least the same color as the other part of the character.

**Comment by tzvetkoff** [comment]
Nice catch!

This is actually a lot nastier than just printing random junk on the last line.
In pixel mode, I assumed that I'll always have an even number of rows, since it's the number of lines in the terminal times 2.
When overridden with `-H {{some odd number}}`, it even references memory outside of the allocated block!
The quick and obvious fix will be to always force even number of rows in pixel mode.

10x again!
